import os
import tempfile
from datetime import datetime, timedelta
import dateparser
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse, FileResponse
from starlette.background import BackgroundTask

import db
import profile_service
from report_generator import render_evaluation_report

router = APIRouter(tags=["Exports & Utilities"])


def _parse_deadline_to_ics_date(deadline_string: str) -> str:
    parsed = dateparser.parse(deadline_string, settings={"PREFER_DATES_FROM": "future"})
    if parsed:
        return parsed.strftime("%Y%m%d")
    return (datetime.now() + timedelta(days=30)).strftime("%Y%m%d")


@router.post("/api/generate-calendar")
async def generate_calendar(
    deadline_string: str,
    org_info: dict = Depends(db.get_current_user_org),
):
    try:
        profile_service.require_complete_profile(db.supabase_client, org_info["org_id"])
    except ValueError as exc:
        raise HTTPException(status_code=403, detail=str(exc)) from exc

    ics_date = _parse_deadline_to_ics_date(deadline_string)
    ics_content = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//TenderSync//Enterprise Engine//EN
BEGIN:VEVENT
SUMMARY:Tender Submission Deadline
DESCRIPTION:Automatically generated by TenderSync. Original extracted deadline text: {deadline_string}
DTSTART;VALUE=DATE:{ics_date}
DTEND;VALUE=DATE:{ics_date}
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR"""
    return PlainTextResponse(
        content=ics_content,
        media_type="text/calendar",
        headers={"Content-Disposition": "attachment; filename=tender_deadline.ics"},
    )


@router.get("/api/tenders/{analysis_id}/export-pdf")
def export_tender_pdf(analysis_id: str, org_info: dict = Depends(db.get_current_user_org)):
    org_id = org_info["org_id"]
    res = db.supabase_client.table("tender_analyses").select("*").eq("id", analysis_id).eq("org_id", org_id).execute()
    if not res.data:
        raise HTTPException(status_code=404, detail="Analysis not found")

    analysis_data = res.data[0]
    company_profile = profile_service.require_complete_profile(db.supabase_client, org_id)

    pdf_bytes = render_evaluation_report(analysis_data, company_profile)

    fd, path = tempfile.mkstemp(suffix=".pdf")
    with os.fdopen(fd, 'wb') as tmp:
        tmp.write(pdf_bytes)

    return FileResponse(
        path,
        media_type="application/pdf",
        filename=f"{analysis_data.get('filename', 'report').replace(' ', '_')}_evaluation.pdf",
        background=BackgroundTask(lambda p: os.remove(p), path)
    )
